#!/usr/bin/env bash
# vim:fdm=marker
#
# Neofetch config file
# https://github.com/dylanaraps/neofetch

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# Info Options {{{


# Info
# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
printinfo() {
    info title
    info underline
    info "OS" distro
    info "Kernel" kernel
    # info "Uptime" uptime
    # info "Packages" packages
    info "Shell" shell
    # info "Resolution" resolution
    info "DE" de
    # info "WM" wm
    # info "WM Theme" wmtheme
    # info "Theme" theme
    # info "Icons" icons
    # info "Terminal" term
    # info "Terminal Font" termfont
    #info "Model" model
    info "Uptime" uptime
    #info "Packages" packages
    #info "Resolution" resolution
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory

    info "CPU Usage" cpu_usage
    info "Disk" disk
    info "Battery" battery
    # info "Font" font
    info linebreak
    info "Song" song
    # info "Local IP" localip
    # info "Public IP" publicip
    # info "Users" users
    # info "Birthday" birthday

    # info linebreak
    # info cols
    # info linebreak
}

kernel_shorthand="on"
distro_shorthand="on"
os_arch="off"


uptime_shorthand="on"

shell_path="off"
shell_version="off"

# CPU

speed_type="bios"
cpu_shorthand="tiny"
cpu_display="off"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="on"
gpu_brand="off"
refresh_rate="off"

gtk_shorthand="on"
gtk2="off"
gtk3="off"

public_ip_host="http://ident.me"

song_shorthand="on"

birthday_shorthand="off"
birthday_time="on"
birthday_format="+%a %d %b %Y %l:%M %p"


# }}}

# Text Colors {{{


# Text Colors
# Each number represents a different part of
# the text in this order:
# title, @, underline, subtitle, colon, info
# colors=(4 6 1 8 8 6)
# You can also specify:
# fg (foreground color)
colors=(2 9 2 2 6 12)


# }}}

# Text Options {{{


# Toggle bold text
# --bold on, off
bold="on"

# Enable/Disable Underline
# --underline on, off
underline_enabled="on"

# Underline character
# --underline_char char
underline_char="-"


# }}}

# Color Blocks {{{


# Color block range
# --block_range start end
start=0
end=7

# Toggle color blocks
# --color_blocks on, off
color_blocks="off"

# Color block width in spaces
# --block_width num
block_width=3

# Color block height in lines
# --block_height num
block_height=1


# }}}

# Progress Bars {{{


# Progress bar character
# --progress_char elapsed_char total_char
progress_char_elapsed="-"
progress_char_total="="

# Progress border
# --progress_border on, off
progress_border="on"

# Progress bar length in spaces
# Number of chars long to make the progress bars.
# --progress_length num
progress_length="15"

# Progress bar colors
# When set to distro, uses your distro's logo colors
# Takes: num, "distro"
# --progress_colors col col
progress_color_elapsed="distro"
progress_color_total="distro"

# Customize how the info is displayed.
# bar: Only the progress bar is displayed.
# infobar: The bar is displayed after the info.
# barinfo: The bar is displayed before the info.
# off: Only the info is displayed.
#
# --memory_display bar, infobar, barinfo, off
# --battery_display bar, infobar, barinfo, off
# --disk_display bar, infobar, barinfo, off
memory_display="off"
battery_display="off"
disk_display="off"


# }}}

# Image Options {{{


# Image Source
# --image wall, ascii, /path/to/img, /path/to/dir/, off
image="wall"

# Thumbnail directory
thumbnail_dir="$HOME/.cache/thumbnails/neofetch"

# W3m-img path
# Only works with the w3m backend.
# Some systems have this in another location
w3m_img_path="/usr/lib/w3m/w3mimgdisplay"

# Crop mode
# --crop_mode normal, fit, fill
crop_mode="normal"

# Crop offset
# Only affects normal mode.
# --crop_offset northwest, north, northeast, west, center
#               east, southwest, south, southeast
crop_offset="center"

# Image size
# The image is half the terminal width by default.
# --size auto, 00px, 00%, none
image_size="auto"

# Right gap between image and text
# --gap num
gap=2

# Image offsets
# Only works with the w3m backend.
# --xoffset px
# --yoffset px
yoffset=0
xoffset=0

# Image background color
# Only works with the w3m backend.
# Unset by default.
# --bg_color 'color', blue
#background_color=


# }}}

# Ascii Options {{{


# Default ascii image to use
# When this is set to distro it will use your
# distro's logo as the ascii.
# --ascii 'distro', path/to/ascii
ascii="distro"

# Ascii distro
# Which distro's ascii art to display.
# --ascii_distro 'auto', 'distro_name'
ascii_distro="auto"

# Ascii colors
# When this is set to distro it will use your
# ditro's colors to color the ascii.
# NOTE: You can also set this to a range of colors
# which will allow you to custom color distro logos
# --ascii_colors distro
# --ascii_colors 2 4 5 6
ascii_colors=(12 2 1 3)

# Logo size
# Arch, Crux and Gentoo have a smaller logo
# variant. Changing the value below to small
# will make neofetch use the small logo.
# --ascii_logo_size small, normal
ascii_logo_size="small"

# Bold ascii logo
# Whether or not to bold the ascii logo.
# --ascii_bold on, off
ascii_bold="on"


# }}}

# Scrot Options {{{


# Whether or not to always take a screenshot
# You can manually take a screenshot with "--scrot" or "-s"
scrot="off"

# Screenshot program to launch
# --scrot_cmd
scrot_cmd="scrot -c -d 3"

# Scrot dir
# Where to save the screenshots
# --scrot_dir /path/to/screenshot/folder
scrot_dir="$HOME/Pictures/"

# Scrot filename
# What to name the screenshots
# --scrot_name str
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"

# Image upload host
# Where to upload the image.
# Possible values: imgur, teknik
image_host="imgur"

# Imgur api key
# This is an api key for neofetch, you can sign up for your own
# here: http://api.imgur.com/oauth2/addclient
imgur_client_id="0e8b44d15e9fc95"


# }}}

# Config Options {{{


# Enable/Disable config file
# --config off, none
config="on"

# Path to custom config file location
# --config path/to/config
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"


# }}}
