stages:
  - deploy

Git MIRROR:
  stage: deploy
  script:
    - git update-index --assume-unchanged .gitlab-ci.yml && git push --mirror https://a1b8f17b34d66397594013805c2472d4ca767389:x-oauth-basic@github.com/acidhunter/dotfiles.git
