Git MIRROR:
  stage: deploy
  script:
    - git remote add github https://github.com/acidhunter/dotfiles.git && git fetch origin && git push github https://$GITHUB_TOKEN:x-oauth-basic@github.com/acidhunter/dotfiles.git