Git MIRROR:
  stage: deploy
  script:
    - git checkout origin/antigen && git pull && git fetch && git push --mirror https://$GITHUB_TOKEN:x-oauth-basic@github.com/acidhunter/dotfiles.git origin/antigen