#!/usr/bin/env bash

set -e


DEFAULT_CONFIG_PREFIX=""
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

#sh sync.sh

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
	# echo "Applying settings for ${conf}..."
	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -v -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}"
	# echo "Done."
done
