source ~/.antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh
antigen bundle robbyrussell/oh-my-zsh lib/


# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle archlinux
antigen bundle ssh-agent
antigen bundle rupa/z
antigen bundle docker
antigen bundle gpg-agent
antigen bundle git-extras
antigen bundle git-flow
antigen bundle pyenv
antigen bundle systemd
antigen bundle sudo
antigen bundle tmux
antigen bundle httpie
antigen bundle catimg
antigen bundle nyan
antigen bundle dirhistory
antigen bundle git
antigen bundle pip
antigen bundle python
antigen bundle virtualenv
antigen bundle lein
antigen bundle command-not-found
antigen bundle desyncr/auto-ls


# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

#antigen theme robbyrussell/oh-my-zsh themes/agnoster
antigen theme eendroroy/alien alien

# Tell Antigen that you're done.
antigen apply


alias ls="ls --color=auto --group-directories-first"
alias shot="scrot -s ~/foo.png && xclip -selection clipboard -target image/png -i < ~/foo.png && rm -f ~/foo.png"
alias spotify="/usr/bin/spotify --force-device-scale-factor=1.5"
export TERMINAL=tilix
