set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/.vim/bundle')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'jnurmine/Zenburn'
Bundle 'ctrlpvim/ctrlp.vim'
Bundle 'wellle/tmux-complete.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'
Plugin 'ap/vim-css-color'
Plugin 'tpope/vim-fugitive'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'prabirshrestha/async.vim'
Plugin 'prabirshrestha/asyncomplete.vim'
" colorschemes
Plugin 'tomasr/molokai'

call vundle#end()            " required
filetype plugin indent on    " required
set backspace=indent,eol,start

set showcmd
set incsearch
set number
set expandtab
set tabstop=2
"set nowrap
set shiftwidth=2
set hlsearch
set ic
set autoindent
set copyindent
set cmdheight=1
set smartcase
set smarttab
set ignorecase
set incsearch
set encoding=utf-8

set history=1000
set undolevels=1000

let python_highlight_all=1
syntax on
set laststatus=2

set pastetoggle=<F2>

set noswapfile
set showmatch

set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

nnoremap ; :

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

let g:rehash256=1

let g:molokai_original=1
colorscheme molokai
set background=dark
let base16colorspace=256
au FileType xml setlocal equalprg=xmllint\ --format\ --recover\ -\ 2>/dev/null
highlight Normal guibg=black guifg=white
highlight Normal ctermbg=none

let g:tmuxcomplete#asyncomplete_source_options = {
            \ 'name':      'tmuxcomplete',
            \ 'whitelist': ['*'],
            \ 'config': {
            \     'splitmode':      'words',
            \     'filter_prefix':   1,
            \     'show_incomplete': 1,
            \     'sort_candidates': 0,
            \     'scrollback':      0,
            \     'truncate':        0
            \     }
            \ }
